#!/bin/bash
rm -rf "pagefile.sys"
rm -rf "swapfile.sys"
rm -rf "hiberfil.sys"

rm -rf "Program Files/Windows Defender"
rm -rf "Program Files (x86)/Windows Defender"
rm -rf "Program Files (x86)/Microsoft"
rm -rf "Program Files (x86)/Internet Explorer"
rm -rf "Program Files/Internet Explorer"
rm -rf "Program Files/Windows Defender Advanced Threat Protection"
rm -rf "Program Files/WindowsApps"

rm -rf "Windows/SystemApps"
rm -rf "Windows/SystemResources/CallingShellApp"
rm -rf "Windows/SystemResources/Microsoft.Windows.SecHealthUI"
rm -rf "Windows/SystemResources/ShellComponents.Switcher"
rm -rf "Windows/SystemResources/Windows.ApplicationModel.LockScreen"
rm -rf "Windows/SystemResources/Windows.Foundation.Diagnostics.ErrorDetails"
rm -rf "Windows/SystemResources/Windows.Management.AutopilotResources"
rm -rf "Windows/SystemResources/Windows.ParentalControlsSettings"
rm -rf "Windows/SystemResources/Windows.ShellCommon.SharedResources"
rm -rf "Windows/SystemResources/Windows.SystemToast.Calling"
rm -rf "Windows/SystemResources/Windows.UI.AccountsControl"
rm -rf "Windows/SystemResources/Windows.UI.BioFeedback"
rm -rf "Windows/SystemResources/Windows.UI.BlockedShutdown"
rm -rf "Windows/SystemResources/Windows.UI.PrintDialog"
rm -rf "Windows/SystemResources/Windows.UI.Search"
rm -rf "Windows/SystemResources/Windows.UI.SettingsAdminFlowUIThreshold"
rm -rf "Windows/SystemResources/Windows.UI.SettingsAppThreshold"
rm -rf "Windows/SystemResources/Windows.UI.SettingsHandler-nt"
rm -rf "Windows/SystemResources/Windows.UI.ShellCommon"
rm -rf "Windows/SystemResources/Windows.UI.ShellCommonInetCore"
rm -rf "Windows/SystemResources/Windows-NFC-SEManagement"
rm -rf "Windows/SystemResources"
rm -rf "Windows/diagnostics"
rm -rf "Windows/DiagTrack"
rm -rf "Windows/Logs"
rm -rf "Windows/Media"
rm -rf "Windows/ShellComponents"
rm -rf "Windows/ShellExperiences"
rm -rf "Windows/WaaS"

rm -rf "Windows/System32/ApplicationFrameHost.exe"
rm -rf "Windows/System32/mobsync.exe"
rm -rf "Windows/System32/WpnUserService.dll"
rm -rf "Windows/System32/cdpusersvc.dll"
rm -rf "Windows/System32/APHostRes.dll"
rm -rf "Windows/System32/APHostClient.dll"
rm -rf "Windows/System32/APHostService.dll"
rm -rf "Windows/System32/upfc.exe"
rm -rf "Windows/System32/dps.dll"
rm -rf "Windows/System32/diagtrack.dll"
rm -rf "Windows/System32/wdi.dll"
rm -rf "Windows/System32/wercplsupport.dll"
rm -rf "Windows/System32/pcasvc.dll"
rm -rf "Windows/System32/MitigationClient.dll"
rm -rf "Windows/System32/wersvc.dll"
rm -rf "Windows/System32/DiagSvcs"
rm -rf "Windows/System32/DiagSvc.dll"
rm -rf "Windows/System32/diagperf.dll"
rm -rf "Windows/System32/lfsvc.dll"
rm -rf "Windows/System32/bcastdvruserservice.dll"
rm -rf "Windows/System32/fhsvc.dll"
rm -rf "Windows/System32/trkwks.dll"
rm -rf "Windows/System32/SecurityHealthSystray.exe"
rm -rf "Windows/System32/SecurityHealthService.exe"
rm -rf "Windows/System32/SecurityHealthAgent.dll"
rm -rf "Windows/System32/smartscreenps.dll"
rm -rf "Windows/System32/smartscreen.exe"


rm -rf "Windows/System32/LogFiles"
rm -rf "Windows/System32/Tasks"

rm -rf "Windows/System32/wups"
rm -rf "Windows/System32/wua"
rm -rf "Windows/System32/AppLockerCSP.dll"
rm -rf "Windows/SysWOW64/AppLockerCSP.dll"
rm -rf "Windows/System32/ClipSVC.dll"
rm -rf "Windows/System32/ClipUp.exe"
rm -rf "Windows/System32/DeviceCensus.exe"
rm -rf "Windows/System32/dmclient.exe"
rm -rf "Windows/System32/omadmclient.exe"
rm -rf "Windows/System32/dosvc.dll"
rm -rf "Windows/System32/Windows.Networking.NetworkOperators.HotspotAuthentication.dll"
rm -rf "Windows/SysWOW64/Windows.Networking.NetworkOperators.HotspotAuthentication.dll"
rm -rf "Windows/System32/invagent.dll"
rm -rf "Windows/System32/msra.exe"
rm -rf "Windows/SysWOW64/msra.exe"
rm -rf "Windows/System32/msrahc.dll"
rm -rf "Windows/System32/SIHClient.exe"
rm -rf "Windows/System32/slui.exe"
rm -rf "Windows/System32/Startupscan.dll"
rm -rf "Windows/SysWOW64/Startupscan.dll"
rm -rf "Windows/System32/StorSvc.dll"
rm -rf "Windows/System32/usoapi.dll"
rm -rf "Windows/SysWOW64/usoapi.dll"
rm -rf "Windows/System32/UsoClient.exe"
rm -rf "Windows/System32/usocoreps.dll"
rm -rf "Windows/System32/usocoreworker.exe"
rm -rf "Windows/System32/MoUsoCoreWorker.exe"
rm -rf "Windows/System32/usocoreworker.exe"
rm -rf "Windows/System32/MoUsoCoreWorker.exe"
rm -rf "Windows/System32/usosvc.dll"
rm -rf "Windows/System32/WaaSMedicPS.dll"
rm -rf "Windows/System32/WaaSMedicSvc.dll"
rm -rf "Windows/System32/WaaSAssessment.dll"
rm -rf "Windows/System32/WaaSMedicAgent.exe"
rm -rf "Windows/System32/WaaSMedicCapsule.dll"
rm -rf "Windows/System32/WindowsUpdateElevatedInstaller.exe"
rm -rf "Windows/System32/wsqmcons.exe"
rm -rf "Windows/System32/wuapi.dll"
rm -rf "Windows/SysWOW64/wuapi.dll"
rm -rf "Windows/System32/wuauclt.exe"
rm -rf "Windows/System32/wuaueng.dll"
rm -rf "Windows/System32/wuapihost.exe"
rm -rf "Windows/System32/storewuauth.dll"
rm -rf "Windows/System32/wusa.exe"
rm -rf "Windows/SysWOW64/wusa.exe"
