rm -rf "pagefile.sys"
rm -rf "swapfile.sys"

rm -rf "Program Files/Windows Defender"
rm -rf "Program Files (x86)/Windows Defender"
rm -rf "Program Files (x86)/Microsoft"
rm -rf "Program Files (x86)/Internet Explorer"
rm -rf "Program Files/Internet Explorer"
rm -rf "Program Files/Windows Defender Advanced Threat Protection"
rm -rf "Program Files/WindowsApps"

rm -rf "Windows/SystemApps"

rm -rf "Windows/System32/ApplicationFrameHost.exe"
rm -rf "Windows/System32/mobsync.exe"
rm -rf "Windows/System32/WpnUserService.dll"
rm -rf "Windows/System32/cdpusersvc.dll"
rm -rf "Windows/System32/APHostRes.dll"
rm -rf "Windows/System32/APHostClient.dll"
rm -rf "Windows/System32/APHostService.dll"
rm -rf "Windows/System32/upfc.exe"
rm -rf "Windows/System32/dps.dll"
rm -rf "Windows/System32/diagtrack.dll"
rm -rf "Windows/System32/wdi.dll"
rm -rf "Windows/System32/wercplsupport.dll"
rm -rf "Windows/System32/pcasvc.dll"
rm -rf "Windows/System32/MitigationClient.dll"
rm -rf "Windows/System32/wersvc.dll"
rm -rf "Windows/System32/DiagSvcs"
rm -rf "Windows/System32/DiagSvc.dll"
rm -rf "Windows/System32/diagperf.dll"
rm -rf "Windows/System32/lfsvc.dll"
rm -rf "Windows/System32/bcastdvruserservice.dll"
rm -rf "Windows/System32/fhsvc.dll"
